apiVersion: v1
kind: Secret
metadata:
    name: ghcr-io-creds
    namespace: discord
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7UwgxsMFDyTW0dxfADHjhQU46c7tH43/ZwbFSQNjx9XGs8U41ankB/ZsXz9EaONxB6BqAm+ZGqMkm2IUOCHx0brwcqcour13TgnvY4ynbTNgzTBMvVthHk1gEPmTCVgxhjlmGO2NNG6T1druKk8HIiAzXQ9ukcoqO8Z/eLkcj/FISRs+mXBeqZVrave9PLAULqaayPUQ6a2fPzbkmi9/bzYWRCi8TJCrGdwVob3/ZYuupjwjrEi6+lABM91rZwXW2E81hwHWymiGv2NR4hS/ZHU89NnyQM+J7EitM3dShYD9Zq3JHE7SoJ5KR3fMqhIj59GM5Z96pefRc5DKaFz6J2YW6WxDtqXd,iv:lvQyca53xy+XuS8Z2oIKacxsqtzJAaUBMDOOqbiXS0o=,tag:K/5dDqsspPmEK+KASvlOWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1muzrgd2s3zmgqwm9x2puzaw6u3rx5ahr2t49genam37wcr3kly8qcma4ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcW00a3N6ZnE0dUxXVHlq
            N0M3RDZpYkhFbkxLUmx3MUR4aURBUDhRdGo4Clk5WlVVSERYU0lEZE1uT01xNlNE
            N2ZGTDBwV2d3UEVPK2lLVWdZeXlWaFEKLS0tIEp2WUUyMTRjdm9uU3pBRU8yUmJJ
            aU5uZmtyUEF5dThEaW5jWndwbVh2SzAK8NCXU5Spb/vzGmxDw1tX/sP2a1sPb5Z3
            cJ1y6TWbg3fbFr4OPysXggOZJ8KQukCu6sn+YKHKmvxmkutz1yjxtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-16T18:26:25Z"
    mac: ENC[AES256_GCM,data:FgFLzqEdxbu1YEEbUlZ1On0aqINjJcPt1XkxHRw5TMgkzkxlm2M9bhhy0J4f1940wm9+be2Np1lh7iBhVRX95cmpn9cEWqPvK3qlHDuW7pdMJi4QCVc0Ikp4Wj3nHhEqu+X21sNABW4nIDI4ipo8yPpMVG0KR3PLVSBjJ02C7CI=,iv:5iqeURdej/x53HYq+0PC05PJMn4rrSbSR0tquYY403g=,tag:BiNOkoBa/2ozNAMs7/EwGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
