---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app stock-ticker
  namespace: discord
spec:
  interval: 10m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/jr0dd/discord-stock-ticker
      tag: v3.10.0@sha256:e83312805f27e3a7a8bb192944bcb391ddaaed470bcb039d4de6e15abadbc7e2
    lifecycle:
      postStart:
        exec:
          command: ["bash", "/config/payload.sh"]
    env:
      TZ: "${TZ}"
    envFrom:
      - secretRef:
          name: discord-tokens
    service:
      main:
        ports:
          http:
            port: 8080
    persistence:
      config:
        enabled: true
        type: configMap
        name: &config payload-config
        defaultMode: 493
    podAnnotations:
      configmap.reloader.stakater.com/reload: *config
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
      limits:
        memory: 100Mi
