apiVersion: v1
kind: Secret
metadata:
    name: discord-tokens
    namespace: discord
type: Opaque
stringData:
    BTC: ENC[AES256_GCM,data:qVEhYQifDwJ5bV9WBR4UNshtBZ9aMq8lVBqUSOOo4QDEp2paxVDPL1XTXLtfao3OiuevMB/dJvA0FAY=,iv:wiGEVYJ5CtmpEPAfDPJt1Tq4fDUYR5aMKYafPLro/IY=,tag:etLv7yRaWrbFNnAfgXZ6Qg==,type:str]
    DOGE: ENC[AES256_GCM,data:fskclOiAvhjoapCGojsipklVI4OoEhBOEhTRrJqQpH5sU472JfekqJ83HirgXIUS8mBbF4WFO8MkO7E=,iv:iTpecRZi2/v/HoXsQ9nbADhxjqbts5ZodYJRYJ8F8RE=,tag:pc+QVLm46m/ivTI+H1JFmQ==,type:str]
    ETH: ENC[AES256_GCM,data:0D/y5/K8X4S0VLbidizqmSAFfQTmSDv+ASuvvEGB+I8upxjVLX02H/CFzjDP7syd6EgOA3sUycy7UPQ=,iv:+F4LweWxE2bMh2r+rEkv9YuM6Bc4A6O4nLNnncFVNzQ=,tag:f4ir/Of3HPih/z4iI2466g==,type:str]
    SHIB: ENC[AES256_GCM,data:6QR72LWsoPb3zk+mYBv1Xr6lxmmIb2cuF76+VyrukAjVXTpQ67HMT6ryDF+eLDskEYvxK8Gkozu58d8=,iv:JyH3olR6X1mUTalO4Jgac/xtjvo/vb2O8ULbOm3Rm1Q=,tag:l3MJok1L4bx+EW0Xxur+4g==,type:str]
    AAPL: ENC[AES256_GCM,data:9tjenX9aK3CsDPZa3tLW81FQs4Lbj9h6HwsOzoxJC8PQfkGTnvqoIrx6ltPIJQTYxTjr9TANnR6Vdb4=,iv:g/hGKN+74oypgoquLKEDAZke7Xs+2LQlX+9L6Kg5GRk=,tag:3VNCSu49qqN+cziLDEnFjA==,type:str]
    DPW: ENC[AES256_GCM,data:j2Hc2TlOfg0vwuzXOg5/XEOZq1rIsAe7NLpSR5tHMCEur2y1SCLznjRsbZ2wCqMW65CQOdclTfP8oUU=,iv:oAXvBeiVDKxTZXmBs7AmjCyDpxzWpWyAG/Szo4LHM1A=,tag:N1ahP7ZUAjOBIrnzTGs1aA==,type:str]
    TSLA: ENC[AES256_GCM,data:32UmF2eeZRqZ4pVu4idIHlEDoVYnC7SzuBfEtFt8Le2t9CkM882RfGYHMeQXXhQBlOhU4UUs0iiU2eg=,iv:7APuIL0h/QFHsdnTAQsvG3s4y+9lcp3cswBOWeZVN5A=,tag:gQQHq76gurGY1KtegpC7xA==,type:str]
    FUTURES: ENC[AES256_GCM,data:d2oq/nTuzqhsPVIGXKFIBNPBOHCE0VHfuN3O404qCoVU6Ic3TAtdAxRwJqHMGyomH+inU+TtXXPXtXA=,iv:2RLoXuw4mO0VYjl+spvelU+8PYS177fK8Ya2hwpqKDc=,tag:tOarIaOsaRewUNjy7289gQ==,type:str]
    INDICES: ENC[AES256_GCM,data:MNduXOuL/QGXZzZg2zWYCc0LeH0OdLsDpaGgzUyi5sWUdtkIpXHDasi/ocVH2RowbUqWjFUSkiKkKvI=,iv:zSG20jnqoWCuh7chl7bFKYegOnCpfU4ovj+h08q+AXw=,tag:8kTF+9WCTRG0xfvGIlf4zw==,type:str]
    MEMES: ENC[AES256_GCM,data:bmeOHQ/bxjljTUyGRI6mjVkC6qMB4Trnx3QC7FmpKQCKY4yDDKkEm8gJLTqupR4xVOZWVMDNNg+1OSk=,iv:Xm2R0VdFfvkUurXroLqZY0hdxHoa9xmZhkFDWQ6L9+M=,tag:L+U0aIfloNpbi4xP8pgRTQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1muzrgd2s3zmgqwm9x2puzaw6u3rx5ahr2t49genam37wcr3kly8qcma4ky
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMFZ2eG4wRWhEM1Vrc2NB
            OExoUEZ5b3ZWSzZNVnp0Q3RqKzFIQnI0SkZzCllOV3NLU01INW0vQS8rVU5rNlI1
            cEdISVlSWGppMVBsc1VoQW5XNFlFWGsKLS0tIE94MWduNEowTENUai9RdWQ3dUtw
            ZDNHTlBVRXB2M3EzSVRKTmw0YTJDL2MKJDkkbu4Lk1n3r9fHbnvIELc9J7T8edE+
            MDqHH1q4STVl76paZKbGd1AIDSbx80zcp/QIYr1BlxDVgmn0koI28A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-16T18:35:36Z"
    mac: ENC[AES256_GCM,data:u3sjVGCrF/JrG38qKO5rT+wjuc6YtQHkRVpPT8wOwdD6/NhyKpeF6HaLTYsP0q1ewwHMzMbZAqS9b+xFbxufwnkIeqcQobeyI3elYYKJc3XsNMSc9I/HTtLU5FBlivpDgFP8jc5rXuVaKR1PsiTAVsLnvcfXKg1OaCqDwZVdHqA=,iv:H79z8pfv50rOVEmvwhDgV4Ib/e7qRATGjB07zVtJ0qw=,tag:C63VfF/gm039oDZK+w1F+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
