---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app puppeteer
  namespace: discord
spec:
  interval: 10m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    controller:
      strategy: RollingUpdate
    image:
      repository: ghcr.io/jr0dd/puppeteer
      tag: v16.2.0@sha256:aef7dc38277e94ac68db65cac561bbb00611a71e40d74e5b2023b7caa9dfa918
      pullPolicy: Always
    env:
      TZ: "${TZ}"
    service:
      main:
        ports:
          http:
            port: &port 9222
    persistence:
      config:
        enabled: false
    ingress:
      main:
        enabled: false
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: &host "puppeteer.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: puppeteer-tls
            hosts:
              - *host
    probes:
      liveness:
        enabled: true
        custom: true
        spec:
          httpGet:
            path: /json/list
            port: *port
    resources:
      requests:
        cpu: 10m
        memory: 100Mi
      limits:
        memory: 750Mi
