---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.2.1
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  dependsOn:
    - name: cert-manager
      namespace: kube-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controller:
      replicaCount: 1
      extraEnvs:
        - name: TZ
          value: "${TZ}"
      service:
        externalTrafficPolicy: Local
      publishService:
        enabled: true
      ingressClassResource:
        default: true
      config:
        client-header-timeout: 120
        client-body-buffer-size: "100M"
        client-body-timeout: 120
        custom-http-errors: >-
          401,403,404,500,501,502,503
        enable-brotli: "true"
        hsts-max-age: "31449600"
        keep-alive: 120
        keep-alive-requests: 10000
        proxy-body-size: 0
        proxy-buffer-size: "16k"
        ssl-protocols: "TLSv1.3 TLSv1.2"
        use-forwarded-headers: "true"
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 350Mi
    defaultBackend:
      enabled: true
      image:
        repository: ghcr.io/tarampampam/error-pages
        tag: 2.18.0
      extraEnvs:
        - name: TEMPLATE_NAME
          value: shuffle
        - name: SHOW_DETAILS
          value: "false"
